### PR TITLE
Use RUBY_CONFIGURE_OPTS instead of CONFIGURE_OPTS

### PR DESCRIPTION
**Pull request by Tagadda**
cc @autra

### CODE REVIEW

**Comment by autra** [comment]
Looks good! Thanks for the help. The full changeset for diaspora_ynh: https://github.com/YunoHost-Apps/diaspora_ynh/pull/40 (note: I still  had to use the LD_PRELOAD workaround)

According to a quick search, here is the list of potiental affected apps (listing all that uses jemalloc), in case it's useful:

- [x] diaspora_ynh
- [ ] mastodon_ynh 
- [ ] redmine_ynh
- [ ] discourse_ynh
- [ ] decidim_ynh
- [ ] ecko_ynh
- [ ] huginn_ynh
- [ ] [glitchsoc_ynh](https://github.com/YunoHost-Apps/glitchsoc_ynh)
- [ ] fab-manager_ynh
- [ ] acropolis_ynh
- [ ] snweb_ynh


There are 2 apps that uses ruby, but don't seem to use jemalloc (maybe we *want* them to use jemalloc?):

- [ ] gollum_ynh
- [ ] foodsoft_ynh

**Comment by autra** [comment]
(NOTE I don't use most of them, but I can open PRs if it helps)

**Comment by autra** [comment]
@Tagadda shouldn't this one get merged?

**Comment by autra** [comment]
Actually, for instance, mastodon_ynh seems to build just fine on bookworm. Maybe it depends on the version of ruby, so not sure if this is needed in all cases.

**Comment by alexAubin** [comment]
(Closing because helper now in the core with RUBY_CONFIGURE_OPTS iirc)

**Pull request closed without merging**
