### PR TITLE
Update Helper from weblate helper

### PR DESCRIPTION
**Pull request by Josue-T**

### CODE REVIEW

**Comment by Jibec** [comment]
Looks good to me, only commit attribution is to be changed, and ljf opinion to be asked.
-- 
Jean-Baptiste Holcroft

**Review by Jibec — CHANGES_REQUESTED** [review]
please change commit attribution

**Comment by maniackcrudelis** [comment]
What do you mean by "change commit attribution" ?

**Comment by Jibec** [comment]
I'm still not good with github, I created a new PR, sorry :(

**Comment by maniackcrudelis** [comment]
So ok, what are we suppose to do with these PR ?
Do I need to merge the second one into this one ?
Or both into master ?

**Pull request closed without merging**
