### PR TITLE
Add check_app_version_changed helper to allow preventing unnecessary upstream app upgrade

### PR DESCRIPTION
**Pull request by JimboJoe**
This helper should be used to avoid an upgrade of the upstream version when it's not needed (but yet allowing to upgrade other parts of the YunoHost application (e.g. nginx conf).

Currently used in [Discourse package](https://github.com/YunoHost-Apps/discourse_ynh/blob/c8a0722de29a7f75aeb8a505f6b7ce0d46dbe1d1/scripts/upgrade#L78).

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
We already have a helper to handle that
https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_abort_if_up_to_date/ynh_abort_if_up_to_date_2

Is this one different ?

**Comment by JimboJoe** [comment]
Yes, it's different in the fact that the upgrade script can make other upgrade actions (change the nginx or other configuration files), while not touching the upstream application itself if not needed.
The mentioned script aborts the upgrade all the way.

**Comment by maniackcrudelis** [comment]
OK
But unless I missed something, the real difference is here there no exit 0.
I think that it would be better to keep only one helper, and merge this one with the existing one.

**Comment by JimboJoe** [comment]
Well, the two scripts don't compare the same things: this one compares the "upstream part" (before ~ynh) of the package versions, whereas the other one compares the global version (and could eventually be managed in the core).

**Comment by maniackcrudelis** [comment]
The existing helper check the whole version number, with ~ynh, but without checking the 2 parts separately.

But, as I understand, if the whole version number don't change, we don't have to update anything.
But, if one or the other part of the version number is different, then we could update a part of the app.

Then, wouldn't be interesting to update the existing helper to be more clever and be able to check the 2 parts of the version number and give an exit code (like this helper) according to what should be done?
Or simply exit if there's nothing to do.

**Comment by JimboJoe** [comment]
Then a principle could be:
Set a `check_app_version_changed` helper that returns:
* `UPSTREAM` if the upstream version has changed
* `YNH_APP` if only the YunoHost app has changed
* exists with `ynh_die` if version unchanged.

Does that sound legit?

**Comment by maniackcrudelis** [comment]
Yes, that sounds good to me

**Review by frju365 — APPROVED** [review]
LGTM

**Review by Josue-T — APPROVED** [review]

**Comment by JimboJoe** [comment]
Here is an attempt to merge the two helpers (unit-tested). What do you think?

**Comment by maniackcrudelis** [comment]
That seems good.
Maybe just change the return values, UPSTREAM_APP and YNH_APP by something clearer about the use case of each of them.
Because these values are going to be used in the upgrade scripts. Maybe something like UPGRADE_APP and UPGRADE_PACKAGE.

**Review by maniackcrudelis — APPROVED** [review]

**Review by maniackcrudelis — APPROVED** [review]

**Review by maniackcrudelis — APPROVED** [review]

**Pull request merged**
