### PR TITLE
Update uwsgi helper

### PR DESCRIPTION
**Pull request by Josue-T**
Tested with [ffsync](https://github.com/YunoHost-Apps/ffsync_ynh) and [pgadmin](https://github.com/YunoHost-Apps/pgadmin_ynh) since many month.

### CODE REVIEW

**Comment by Josue-T** [comment]
Ping ?

**Comment by maniackcrudelis** [comment]
ping @Jibec ?
Ask for someone if you expect a review.
No one reviews experimental helpers otherwise.

**Comment by Jibec** [comment]
I'm fine with Josue updating the helper. I suggest to put his name as 
point of contact for eventual help.

My time to contribute to YunoHost is really limited. I'll try to test it 
on weblate application someday. Don't wait for me.
Thanks for all you work.

**Comment by yalh76** [comment]
@Josue-T do you agree with the changes I made ?

**Pull request merged**
