### PR TITLE
Allow reading service logs from systemd journal

### PR DESCRIPTION
**Pull request by JimboJoe**
Use systemd journal for log inputs if specified log file is "systemd".

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Seems good to me, just one thing, have you checked the value get by $pid_tail, to be sure there's no problem with the if ?

**Comment by JimboJoe** [comment]
`$pid_tail` gets the right pid.

Not specifically related to this PR, the `ynh_clean_check_starting` isn't found in my scripts when used in the `ynh_clean_setup` used by `ynh_abort_if_errors`; I had to put it out of `ynh_check_starting`...
Did it ever work for you, did I miss something...?

**Comment by maniackcrudelis** [comment]
Hum, the question would be, is a function is available outside of the scope of another function...
I'm not sure though, and maybe the better thing would be to put this function outside to be sure.

**Comment by maniackcrudelis** [comment]
As soon as it's ok for you, merge, it's an experimental helper, no reason to bother us with long reviews.

**Pull request merged**
